services:
  - type: web
    name: loto-api
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000   
    runtime: python-3.11
